# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fault-remediation-module.fullname" . }}
  labels:
    {{- include "fault-remediation-module.labels" . | nindent 4}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fault-remediation-module.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with ((.Values.global).podAnnotations | default .Values.podAnnotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fault-remediation-module.selectorLabels" . | nindent 8 }}
    spec:
      {{- with ((.Values.global).imagePullSecrets | default .Values.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fault-remediation-module.serviceAccountName" . }}
      {{- if eq .Values.global.datastore.provider "postgresql" }}
      initContainers:
        - name: fix-cert-permissions
          image: "docker.io/bitnamilegacy/os-shell:12-debian-12-r30"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
          command:
            - sh
            - -c
            - |
              echo "Copying PostgreSQL client certificates with correct permissions..."
              cp /etc/ssl/client-certs-original/tls.crt /etc/ssl/client-certs-fixed/
              cp /etc/ssl/client-certs-original/ca.crt /etc/ssl/client-certs-fixed/
              cp /etc/ssl/client-certs-original/tls.key /etc/ssl/client-certs-fixed/
              chmod 644 /etc/ssl/client-certs-fixed/tls.crt
              chmod 644 /etc/ssl/client-certs-fixed/ca.crt
              chmod 600 /etc/ssl/client-certs-fixed/tls.key
              echo "Certificate permissions fixed:"
              ls -la /etc/ssl/client-certs-fixed/
          volumeMounts:
            - name: postgresql-client-cert-original
              mountPath: /etc/ssl/client-certs-original
              readOnly: true
            - name: client-certs-fixed
              mountPath: /etc/ssl/client-certs-fixed
      {{- end }}
      containers:
        - name: fault-remediation
          image: "{{ ((.Values.global).faultRemediationModule).image.repository | default "ghcr.io/nvidia/nvsentinel-fault-remediation-module" }}:{{ ((.Values.global).image).tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ ((.Values.global).faultRemediationModule).image.pullPolicy | default "IfNotPresent" }}
          {{- if eq .Values.global.datastore.provider "postgresql" }}
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
          - "--dry-run={{ ((.Values.global).dryRun) | default false }}"
          ports:
            - name: metrics
              containerPort: {{ ((.Values.global).metricsPort) | default 2112 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
          {{- if eq .Values.global.datastore.provider "postgresql" }}
          - name: client-certs-fixed
            mountPath: {{ .Values.clientCertMountPath }}
            readOnly: true
          {{- else }}
          - name: mongo-app-client-cert
            mountPath: {{ .Values.clientCertMountPath }}
            readOnly: true
          {{- end }}
          - name: templates
            mountPath: {{ .Values.maintenanceResource.template.mountPath }}
          env:
          - name: MAINTENANCE_NAMESPACE
            value: {{ .Values.maintenanceResource.namespace }}
          - name: MAINTENANCE_VERSION
            value: {{ .Values.maintenanceResource.version }}
          - name: MAINTENANCE_API_GROUP
            value: {{ .Values.maintenanceResource.apiGroup }}
          {{- if eq .Values.global.datastore.provider "postgresql" }}
          - name: POSTGRESQL_CLIENT_CERT_MOUNT_PATH
            value: {{ .Values.clientCertMountPath }}
          {{- else }}
          - name: MONGODB_CLIENT_CERT_MOUNT_PATH
            value: {{ .Values.clientCertMountPath }}
          {{- end }}
          - name: TEMPLATE_MOUNT_PATH
            value: {{ .Values.maintenanceResource.template.mountPath }}
          - name: TEMPLATE_FILE_NAME
            value: {{ .Values.maintenanceResource.template.fileName }}
          - name: ENABLE_LOG_COLLECTOR
            value: "{{ .Values.logCollector.enabled }}"
          - name: LOG_COLLECTOR_MANIFEST_PATH
            value: {{ .Values.maintenanceResource.template.mountPath }}/{{ .Values.logCollector.manifestFileName }}
          - name: ENABLE_GCP_SOS_COLLECTION
            value: "{{ .Values.logCollector.enableGcpSosCollection }}"
          - name: LOG_LEVEL
            value: "{{ .Values.logLevel }}"
          envFrom:
          - configMapRef:
              name: {{ if .Values.global.datastore }}{{ .Release.Name }}-datastore-config{{ else }}mongodb-config{{ end }}
              optional: true
      volumes:
      {{- if eq .Values.global.datastore.provider "postgresql" }}
      - name: postgresql-client-cert-original
        secret:
          secretName: postgresql-client-cert
          optional: true
      - name: client-certs-fixed
        emptyDir: {}
      {{- else }}
      - name: mongo-app-client-cert
        secret:
          secretName: mongo-app-client-cert-secret
          optional: true
      {{- end }}
      - name: templates
        configMap:
          name: fault-remediation-templates
          items:
            - key: {{ .Values.maintenanceResource.template.fileName }}
              path: {{ .Values.maintenanceResource.template.fileName }}
            {{- if .Values.logCollector.enabled }}
            - key: {{ .Values.logCollector.manifestFileName }}
              path: {{ .Values.logCollector.manifestFileName }}
            {{- end }}
      restartPolicy: Always
      {{- with (((.Values.global).systemNodeSelector) | default .Values.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (((.Values.global).affinity) | default .Values.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (((.Values.global).systemNodeTolerations) | default .Values.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
